[book]
title = "gsn2x User Manual"
description = "gsn2x User Manual"
authors = ["Jonas Wolf <jonas.wolf@jonaswolf.org>"]
language = "en"


[build]
create-missing = false
build-dir = "book"
extra-watch-dirs = ["../examples"]

[output.html]
additional-css = ["svg.css"]
